###

@baseURL = http://localhost:8080
@username = admin@admin.cl
@password = admin1234


###
GET {{ baseURL }}/11/11/me?id=61d3e6cf08edfb99206abb68 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWQzZTZjZjA4ZWRmYjk5MjA2YWJiNjgiLCJiaW9ncmFwaGljIjoiIiwiYmlydGhkYXkiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY2wiLCJleHAiOjE2NDE0OTY4MDIsImxvY2F0aW9uIjoiIiwibmFtZSI6IiIsInN1cm5hbWUiOiIiLCJ3ZWJzaXRlIjoiIn0.i7eWoP-G5L6gWakZCKd7gV1ufHJ0oZnKxQCDXEDwkgU

###
GET {{ baseURL }}/tweets/{{ tweetID }} HTTP/1.1

###
POST {{ baseURL }}/signUp HTTP/1.1
Content-Type: application/json

{
  "email": "{{ username }}",
  "password": "{{ password }}"
}

###
POST {{ baseURL }}/signIn HTTP/1.1
Content-Type: application/json

{
  "email": "{{ username }}",
  "password": "{{ password }}"
}
